version: "2.1"
services:
  redis:
    image: redis:2.8
    container_name: "messaging.redis"
    ports:
      - "6379:6379"
    networks:
      - devstack_default

  channel-messaging:
    image: channel-messaging
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messaging
    volumes:
      - .:/edx/app/messaging/messaging
    command: bash -c 'while true; do python /edx/app/messaging/messaging/manage.py runserver 0.0.0.0:8765; sleep 2; done'
    ports:
      - "8765:8765"
    networks:
      - devstack_default
    depends_on:
      - redis
    stdin_open: true
    tty: true

networks:
  devstack_default:
    external: true
