# db:
#   image: mysql:5.6
#   container_name: db
#   environment:
#     MYSQL_ROOT_PASSWORD: ""
#     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
version: "2.1"
services:
  channel-messaging:
    image: channel-messaging
    build:
      context: .
      dockerfile: Dockerfile

    container_name: messaging
    volumes:
      - .:/edx/app/messaging/messaging

    command: bash -c 'while true; do python /edx/app/messaging/messaging/manage.py runserver 0.0.0.0:8765; sleep 2; done'

    ports:
      - "8765:8765"

    networks:
      - devstack_default

    stdin_open: true
    tty: true

networks:
  devstack_default:
    external: true
